[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false
serverAddress = "guardiansoftruth.streamlit.app"

[theme]
primaryColor = "#17c6d8"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0f0f14"
textColor = "#ffffff"
font = "sans serif"
base = "dark"
